# Generated by Django 3.1.3 on 2021-02-28 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_inicial', models.DateField(blank=True, null=True)),
                ('fecha_final', models.DateField(blank=True, null=True)),
                ('variantes', models.TextField(default=None, max_length=50)),
                ('subtitulo', models.TextField(default=None, max_length=50)),
                ('texto', models.TextField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
