# Generated by Django 3.1.3 on 2021-04-01 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20210401_2353'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Monthly_Report',
        ),
        migrations.AddField(
            model_name='report',
            name='fecha_final',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='fecha_inicial',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='subtitulo',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='texto',
            field=models.TextField(blank=True, default=None, max_length=50),
        ),
        migrations.AddField(
            model_name='report',
            name='variantes',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
