# Generated by Django 3.1.3 on 2021-04-02 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_auto_20210401_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='texto',
        ),
        migrations.RemoveField(
            model_name='report',
            name='variantes',
        ),
        migrations.AddField(
            model_name='report',
            name='texto_geolocalizacion_concellos',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='texto_informacion',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='texto_procedencia',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='texto_variantes_columnas',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='texto_variantes_lineas',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
    ]
