# Generated by Django 3.1.3 on 2021-04-02 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20210402_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='fecha_final',
            field=models.DateField(default='2020-01-30'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fecha_inicial',
            field=models.DateField(default='2020-01-01'),
        ),
    ]
