# Generated by Django 3.1.3 on 2021-04-02 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_auto_20210402_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='fecha_publ',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='report',
            name='objetivo',
            field=models.CharField(default='vigilancia', max_length=10),
        ),
        migrations.AddField(
            model_name='report',
            name='tipo',
            field=models.CharField(default='mensual', max_length=10),
        ),
    ]
