# Generated by Django 3.1.3 on 2021-04-02 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20210402_0014'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='texto_variantes_galicia',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
        migrations.AddField(
            model_name='report',
            name='texto_variantes_hospitales',
            field=models.TextField(blank=True, default=None, max_length=600),
        ),
    ]
