# Generated by Django 3.1.3 on 2021-04-02 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_auto_20210402_0112'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=10),
        ),
    ]
