# Generated by Django 3.1.3 on 2021-04-02 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_report_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='titulo',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
