# Generated by Django 3.1.3 on 2021-05-06 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_auto_20210402_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='objetivo',
        ),
        migrations.AddField(
            model_name='report',
            name='categoria',
            field=models.CharField(default='vigilancia', max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='tipo',
            field=models.CharField(choices=[('privado', 'privado'), ('mensual', 'mensual'), ('general', 'general')], default='mensual', max_length=10),
        ),
    ]
