# Generated by Django 3.1.3 on 2021-05-06 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_auto_20210506_2152'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='umbral',
            field=models.IntegerField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='report',
            name='categoria',
            field=models.CharField(choices=[('vigilancia', 'vigilancia'), ('aleatoria', 'aleatoria'), ('no aleatoria', 'no aleatoria')], default='vigilancia', max_length=20),
        ),
    ]
