# Generated by Django 3.1.3 on 2021-05-06 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0011_auto_20210506_2154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='umbral',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
