# Generated by Django 3.1.3 on 2021-06-27 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_auto_20210506_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='encrypted_url_code',
            field=models.TextField(default='Obtener este código desde el apartado de gráficas', max_length=600),
        ),
    ]
