# Generated by Django 3.1.3 on 2021-06-27 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_report_encrypted_url_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='umbral',
        ),
    ]
