# Generated by Django 3.1.3 on 2020-11-23 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.TextField()),
                ('image', models.ImageField(upload_to='images/')),
                ('body', models.TextField(max_length=300)),
            ],
        ),
    ]
