# Generated by Django 3.1.3 on 2020-11-24 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20201124_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='buttons',
            field=models.TextField(default='fill'),
            preserve_default=False,
        ),
    ]
