# Generated by Django 3.1.3 on 2020-11-26 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_task_buttons'),
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id_region', models.AutoField(primary_key=True, serialize=False)),
                ('cp', models.IntegerField()),
                ('location', models.TextField(max_length=50)),
                ('country', models.TextField(default='SPAIN', max_length=50)),
                ('region', models.TextField(default='EUROPE', max_length=50)),
            ],
            options={
                'unique_together': {('cp', 'location')},
            },
        ),
    ]
