# Generated by Django 3.1.3 on 2020-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='location',
            field=models.CharField(max_length=50),
        ),
    ]
