# Generated by Django 3.1.3 on 2020-11-26 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_auto_20201126_0025'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.TextField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
