# Generated by Django 3.1.3 on 2020-11-26 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_auto_20201126_0040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.TextField(max_length=50, null='NULL'),
        ),
    ]
