# Generated by Django 3.1.3 on 2020-11-26 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_auto_20201126_0119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='region',
            name='longitude',
        ),
    ]
