# Generated by Django 3.1.3 on 2020-11-26 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20201126_0122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.TextField(max_length=50),
        ),
    ]
