# Generated by Django 3.1.3 on 2020-11-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_auto_20201126_0129'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='latitude',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AddField(
            model_name='region',
            name='longitude',
            field=models.TextField(default='NULL', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='country',
            field=models.TextField(default='SPAIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='region',
            field=models.TextField(default='EUROPE', max_length=50),
        ),
    ]
