# Generated by Django 3.1.3 on 2020-11-26 02:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0012_auto_20201126_0130'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
