# Generated by Django 3.1.3 on 2020-11-26 02:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_region'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Region',
        ),
    ]
