# Generated by Django 3.1.3 on 2021-02-06 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_delete_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='show_to',
            field=models.TextField(blank=True, default=None, max_length=10),
        ),
    ]
