# Generated by Django 3.1.3 on 2021-02-28 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_task_show_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(blank=True, default=None, max_length=150)),
                ('descripción', models.TextField(blank=True, default=None, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Team_Component',
            fields=[
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tasks.team')),
                ('person', models.CharField(blank=True, default=None, max_length=30)),
            ],
        ),
    ]
