# Generated by Django 3.1.3 on 2021-02-28 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0019_team_team_component'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='id',
            new_name='id_team',
        ),
        migrations.DeleteModel(
            name='Team_Component',
        ),
    ]
