# Generated by Django 3.1.3 on 2021-02-28 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0021_team_component'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team_component',
            name='id_team',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
        migrations.DeleteModel(
            name='Team_Component',
        ),
    ]
