# Generated by Django 3.1.3 on 2021-03-17 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0024_auto_20210317_0459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='image',
            field=models.ImageField(upload_to='tasks'),
        ),
    ]
