# Generated by Django 3.1.3 on 2020-11-30 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OurSampleCharacteristics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_patient', models.IntegerField()),
                ('numero_envio', models.IntegerField()),
                ('id_tube', models.CharField(max_length=20)),
                ('id_sample', models.IntegerField()),
                ('hospitalizacion', models.CharField(max_length=1)),
                ('uci', models.CharField(max_length=1)),
                ('ct_orf1ab', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ct_gen_e', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ct_gen_n', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ct_redrp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fecha_sintomas', models.DateField()),
                ('fecha_diagnostico', models.DateField()),
                ('fecha_entrada_uv', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Samples',
            fields=[
                ('id_sample', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_accession', models.CharField(max_length=20)),
                ('original_name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=1)),
                ('patient_status', models.CharField(max_length=20)),
                ('originating_lab', models.CharField(max_length=20)),
                ('collection_date', models.DateField()),
                ('additional_info', models.TextField(max_length=50)),
                ('data_path', models.FileField(storage='uploads/', upload_to='')),
            ],
        ),
        migrations.RenameModel(
            old_name='Region',
            new_name='Regions',
        ),
    ]
