# Generated by Django 3.1.3 on 2020-11-30 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0002_auto_20201130_1743'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurSampleCharacteristics',
            new_name='OurSampleCharacteristic',
        ),
        migrations.RenameModel(
            old_name='Regions',
            new_name='Region',
        ),
        migrations.RenameModel(
            old_name='Samples',
            new_name='Sample',
        ),
    ]
