# Generated by Django 3.1.3 on 2020-11-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0003_auto_20201130_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitude',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitude',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='additional_info',
            field=models.TextField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(default=None),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='sample',
            name='data_path',
            field=models.FileField(default=None, storage='uploads/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gender',
            field=models.CharField(default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_accession',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='original_name',
            field=models.CharField(default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='originating_lab',
            field=models.CharField(default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_status',
            field=models.CharField(default=None, max_length=20),
        ),
    ]
