# Generated by Django 3.1.3 on 2020-11-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0004_auto_20201130_1950'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='id_sample',
            new_name='id_uvigo',
        ),
        migrations.RemoveField(
            model_name='oursamplecharacteristic',
            name='id',
        ),
        migrations.AddField(
            model_name='oursamplecharacteristic',
            name='id_uvigo',
            field=models.CharField(default='NULL', max_length=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='id_patient',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='id_tube',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='numero_envio',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='additional_info',
            field=models.TextField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='sample',
            name='collection_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='sample',
            name='data_path',
            field=models.FileField(blank=True, default=None, storage='uploads/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='gender',
            field=models.CharField(blank=True, default=None, max_length=1),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_accession',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='original_name',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='originating_lab',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_status',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
