# Generated by Django 3.1.3 on 2020-11-30 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0005_auto_20201130_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='id_uvigo',
            new_name='id_sample',
        ),
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='id_sample',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
