# Generated by Django 3.1.3 on 2020-12-01 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0007_auto_20201130_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='id_patient',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='oursamplecharacteristic',
            name='id_sample',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
