# Generated by Django 3.1.3 on 2020-12-01 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0008_auto_20201201_0006'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='id_region',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
