# Generated by Django 3.1.3 on 2021-02-10 21:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0009_sample_id_region'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oursamplecharacteristic',
            old_name='id_sample',
            new_name='id_muestra',
        ),
        migrations.RenameField(
            model_name='oursamplecharacteristic',
            old_name='id_tube',
            new_name='id_tubo',
        ),
    ]
