# Generated by Django 3.1.3 on 2021-02-10 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0010_auto_20210210_2154'),
    ]

    operations = [
        migrations.RenameField(
            model_name='oursamplecharacteristic',
            old_name='id_patient',
            new_name='id_paciente',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='location',
            new_name='localizacion',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='age',
            new_name='edad',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='collection_date',
            new_name='fecha_muestra',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='originating_lab',
            new_name='nodo_secuenciación',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='additional_info',
            new_name='observaciones',
        ),
        migrations.RenameField(
            model_name='sample',
            old_name='gender',
            new_name='sexo',
        ),
        migrations.AlterUniqueTogether(
            name='region',
            unique_together={('cp', 'localizacion')},
        ),
    ]
