# Generated by Django 3.1.3 on 2021-02-10 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0011_auto_20210210_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='oursamplecharacteristic',
            name='id_hospital',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
