# Generated by Django 3.1.3 on 2021-02-10 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0013_auto_20210210_2205'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OurSampleCharacteristic',
            new_name='SampleMetaData',
        ),
    ]
