# Generated by Django 3.1.3 on 2021-02-10 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0014_auto_20210210_2211'),
    ]

    operations = [
        migrations.RenameField(
            model_name='region',
            old_name='latitude',
            new_name='latitud',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='longitude',
            new_name='longitud',
        ),
        migrations.RenameField(
            model_name='region',
            old_name='country',
            new_name='pais',
        ),
    ]
