# Generated by Django 3.1.3 on 2021-02-10 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0015_auto_20210210_2224'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='nodo_secuenciación',
            new_name='nodo_secuenciacion',
        ),
    ]
