# Generated by Django 3.1.3 on 2021-02-10 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0016_auto_20210210_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='fecha_muestra',
            field=models.DateField(blank=True, null=True),
        ),
    ]
