# Generated by Django 3.1.3 on 2021-02-10 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0017_auto_20210210_2252'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_diagnostico',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_entrada_fastq_uvigo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_entrada_uv',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_envio_cdna',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_run_ngs',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='fecha_sintomas',
            field=models.DateField(blank=True, null=True),
        ),
    ]
