# Generated by Django 3.1.3 on 2021-02-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0018_auto_20210210_2343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='ct_gen_e',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='ct_gen_n',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='ct_orf1ab',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='ct_redrp',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='ct_s',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True),
        ),
    ]
