# Generated by Django 3.1.3 on 2021-03-02 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0019_auto_20210211_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='prueba_model',
            fields=[
                ('atr1', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('atr2', models.CharField(blank=True, default=None, max_length=20)),
            ],
        ),
    ]
