# Generated by Django 3.1.3 on 2021-03-02 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0020_prueba_model'),
    ]

    operations = [
        migrations.DeleteModel(
            name='prueba_model',
        ),
    ]
