# Generated by Django 3.1.3 on 2021-03-02 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0021_delete_prueba_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemetadata',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='id_uvigo',
            field=models.CharField(max_length=20),
        ),
    ]
