# Generated by Django 3.1.3 on 2021-03-02 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0022_auto_20210302_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemetadata',
            name='id',
        ),
        migrations.AlterField(
            model_name='samplemetadata',
            name='id_uvigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
