# Generated by Django 3.1.3 on 2021-03-02 22:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0023_auto_20210302_2228'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleMetaData',
        ),
    ]
