# Generated by Django 3.1.3 on 2021-03-02 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0024_delete_samplemetadata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SampleMetaData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_uvigo', models.CharField(max_length=20)),
                ('id_paciente', models.CharField(blank=True, default=None, max_length=20)),
                ('id_hospital', models.CharField(blank=True, default=None, max_length=20)),
                ('numero_envio', models.IntegerField(blank=True, default=0)),
                ('id_tubo', models.CharField(blank=True, default=None, max_length=20)),
                ('id_muestra', models.CharField(blank=True, default=None, max_length=20)),
                ('hospitalizacion', models.CharField(max_length=1)),
                ('uci', models.CharField(max_length=1)),
                ('ct_orf1ab', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('ct_gen_e', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('ct_gen_n', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('ct_redrp', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('ct_s', models.DecimalField(decimal_places=2, default=None, max_digits=5, null=True)),
                ('fecha_envio_cdna', models.DateField(blank=True, null=True)),
                ('fecha_run_ngs', models.DateField(blank=True, null=True)),
                ('fecha_entrada_fastq_uvigo', models.DateField(blank=True, null=True)),
                ('fecha_sintomas', models.DateField(blank=True, null=True)),
                ('fecha_diagnostico', models.DateField(blank=True, null=True)),
                ('fecha_entrada_uv', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
