# Generated by Django 3.1.3 on 2021-03-02 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0025_samplemetadata'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SampleMetaData',
        ),
    ]
