# Generated by Django 3.1.3 on 2021-03-02 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0027_samplemetadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='id_uvigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample'),
        ),
    ]
