# Generated by Django 3.1.3 on 2021-03-03 03:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0030_sample_id_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='id_region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.region'),
        ),
    ]
