# Generated by Django 3.1.3 on 2021-03-08 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_auto_20210303_0301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='nodo_secuenciacion',
            field=models.CharField(blank=True, default=None, max_length=50),
        ),
        migrations.AlterField(
            model_name='sample',
            name='observaciones',
            field=models.TextField(blank=True, default=None, max_length=100),
        ),
    ]
