# Generated by Django 3.1.3 on 2021-03-08 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0035_samplemetadata_categoria_muestra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='samplemetadata',
            name='categoria_muestra',
        ),
    ]
