# Generated by Django 3.1.3 on 2021-03-08 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0036_remove_samplemetadata_categoria_muestra'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='categoria_muestra',
            field=models.CharField(blank=True, default=None, max_length=20),
        ),
    ]
