# Generated by Django 3.1.3 on 2021-03-14 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0037_sample_categoria_muestra'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='categoria_muestra',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='data_path',
            field=models.FileField(blank=True, default=None, null=True, storage='uploads/', upload_to=''),
        ),
        migrations.AlterField(
            model_name='sample',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_accession',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='id_region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='upload.region'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='nodo_secuenciacion',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='observaciones',
            field=models.TextField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='original_name',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='patient_status',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sexo',
            field=models.CharField(blank=True, default=None, max_length=1, null=True),
        ),
    ]
