# Generated by Django 3.1.3 on 2021-04-05 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0039_auto_20210405_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='edad',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
