# Generated by Django 3.1.3 on 2021-04-11 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0041_auto_20210410_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitud',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitud',
            field=models.TextField(default=None, max_length=50, null=True),
        ),
    ]
