# Generated by Django 3.1.3 on 2021-04-14 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0043_auto_20210411_2245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='id_tubo',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
