# Generated by Django 3.1.3 on 2021-04-14 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0045_auto_20210414_0159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='cp',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='localizacion',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
