# Generated by Django 3.1.3 on 2021-04-19 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0046_auto_20210414_0223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='nodo_secuenciacion',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
