# Generated by Django 3.1.3 on 2021-04-19 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0049_auto_20210419_0039'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='nodo_secuenciacion',
            field=models.CharField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
