# Generated by Django 3.1.3 on 2021-05-10 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0051_auto_20210421_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='division',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
    ]
