# Generated by Django 3.1.3 on 2021-05-29 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0053_auto_20210525_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemetadata',
            name='calidad_secuenciacion',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='vacunacion_dosis',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='vacunacion_tipo',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
