# Generated by Django 3.1.3 on 2021-07-10 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0056_auto_20210531_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='samplemetadata',
            name='numero_envio',
            field=models.CharField(blank=True, default=None, max_length=20, null=True),
        ),
    ]
