# Generated by Django 3.1.3 on 2021-07-13 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0057_auto_20210710_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='samplemetadata',
            name='qc_numero_mutaciones',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='samplemetadata',
            name='qc_vaf',
            field=models.CharField(blank=True, default=None, max_length=30, null=True),
        ),
    ]
