# Generated by Django 3.1.12 on 2021-08-16 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0058_auto_20210713_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='latitud',
            field=models.FloatField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='region',
            name='longitud',
            field=models.FloatField(blank=True, default=None, max_length=50, null=True),
        ),
    ]
