# Generated by Django 3.1.3 on 2020-12-02 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_task', models.CharField(choices=[('O', 'OnGoing'), ('C', 'Completed'), ('S', 'Stored'), ('F', 'Failed')], max_length=40)),
                ('command', models.TextField(max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('date', models.DateTimeField()),
                ('elapsed_time', models.IntegerField()),
            ],
        ),
    ]
