# Generated by Django 3.1.3 on 2020-12-03 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='status',
            name='id',
        ),
        migrations.AlterField(
            model_name='status',
            name='id_task',
            field=models.CharField(max_length=40, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='status',
            name='status',
            field=models.CharField(choices=[('O', 'OnGoing'), ('C', 'Completed'), ('S', 'Stored'), ('F', 'Failed')], max_length=20),
        ),
    ]
