# Generated by Django 3.1.3 on 2021-02-12 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0002_auto_20201203_0046'),
    ]

    operations = [
        migrations.RenameField(
            model_name='status',
            old_name='id_task',
            new_name='id_process',
        ),
    ]
