# Generated by Django 3.1.3 on 2021-06-19 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0003_auto_20210212_1607'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Status',
        ),
    ]
