# Generated by Django 3.1.3 on 2021-06-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobstatus', '0005_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='comentario',
            field=models.TextField(max_length=500),
        ),
    ]
