# Generated by Django 3.1.3 on 2021-02-09 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineagesTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('lineage', models.CharField(max_length=10)),
                ('probability', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pangolearn_version', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='NextcladeTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('total_missing', models.IntegerField()),
                ('clade', models.TextField()),
                ('qc_private_mutations_status', models.TextField()),
                ('qc_missing_data_status', models.TextField()),
                ('qc_snp_clusters_status', models.TextField()),
                ('qc_mixed_sites_status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NGSstatsTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('total_reads', models.IntegerField()),
                ('mapped', models.IntegerField()),
                ('trimmed', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SingleCheckTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('autocorrelation', models.DecimalField(decimal_places=10, max_digits=15)),
                ('variation_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('gini_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('mad', models.DecimalField(decimal_places=10, max_digits=15)),
            ],
        ),
        migrations.CreateModel(
            name='VariantsTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=10)),
                ('alt', models.CharField(max_length=10)),
                ('alt_freq', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ref_codon', models.CharField(max_length=10)),
                ('ref_aa', models.CharField(max_length=10)),
                ('alt_codon', models.CharField(max_length=10)),
                ('alt_aa', models.CharField(max_length=10)),
            ],
        ),
        migrations.RenameModel(
            old_name='PicardTests',
            new_name='PicardTest',
        ),
    ]
