# Generated by Django 3.1.3 on 2021-02-12 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_auto_20210209_0003'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicardTest',
        ),
    ]
