# Generated by Django 3.1.3 on 2021-02-12 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_delete_picardtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicardTest',
            fields=[
                ('id_test', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('mean_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('median_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('pct_target_bases_1x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_10x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_100x', models.DecimalField(decimal_places=6, max_digits=7)),
            ],
        ),
    ]
