# Generated by Django 3.1.3 on 2021-02-12 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0004_picardtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PicardTest',
        ),
    ]
