# Generated by Django 3.1.3 on 2021-02-12 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0005_delete_picardtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineagesTest',
        ),
        migrations.DeleteModel(
            name='NextcladeTest',
        ),
        migrations.DeleteModel(
            name='NGSstatsTest',
        ),
        migrations.DeleteModel(
            name='SingleCheckTest',
        ),
        migrations.DeleteModel(
            name='VariantsTest',
        ),
    ]
