# Generated by Django 3.1.3 on 2021-02-12 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0007_lineagestest_nextcladetest_ngsstatstest_picardtest_singlechecktest_variantstest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineagesTest',
        ),
        migrations.DeleteModel(
            name='NextcladeTest',
        ),
        migrations.DeleteModel(
            name='NGSstatsTest',
        ),
        migrations.DeleteModel(
            name='PicardTest',
        ),
        migrations.DeleteModel(
            name='SingleCheckTest',
        ),
        migrations.DeleteModel(
            name='VariantsTest',
        ),
    ]
