# Generated by Django 3.1.3 on 2021-02-12 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0008_auto_20210212_1717'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantsTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=10)),
                ('alt', models.CharField(max_length=10)),
                ('alt_freq', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ref_codon', models.CharField(max_length=10)),
                ('ref_aa', models.CharField(max_length=10)),
                ('alt_codon', models.CharField(max_length=10)),
                ('alt_aa', models.CharField(max_length=10)),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
        migrations.CreateModel(
            name='SingleCheckTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('autocorrelation', models.DecimalField(decimal_places=10, max_digits=15)),
                ('variation_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('gini_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('mad', models.DecimalField(decimal_places=10, max_digits=15)),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
        migrations.CreateModel(
            name='PicardTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('mean_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('median_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('pct_target_bases_1x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_10x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_100x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NGSstatsTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('total_reads', models.IntegerField()),
                ('mapped', models.IntegerField()),
                ('trimmed', models.IntegerField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
        migrations.CreateModel(
            name='NextcladeTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('total_missing', models.IntegerField()),
                ('clade', models.TextField()),
                ('qc_private_mutations_status', models.TextField()),
                ('qc_missing_data_status', models.TextField()),
                ('qc_snp_clusters_status', models.TextField()),
                ('qc_mixed_sites_status', models.TextField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
        migrations.CreateModel(
            name='LineagesTest',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('lineage', models.CharField(max_length=10)),
                ('probability', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pangolearn_version', models.CharField(blank=True, max_length=15)),
                ('comments', models.TextField(blank=True, default=None, max_length=50)),
                ('date', models.DateTimeField()),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
    ]
