# Generated by Django 3.1.3 on 2021-02-12 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0009_lineagestest_nextcladetest_ngsstatstest_picardtest_singlechecktest_variantstest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagestest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='nextcladetest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='ngsstatstest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='picardtest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='singlechecktest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='variantstest',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
