# Generated by Django 3.1.3 on 2021-02-12 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0010_auto_20210212_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineagestest',
            name='most_common_countries',
            field=models.TextField(blank=True, default=None, max_length=50),
        ),
    ]
