# Generated by Django 3.1.3 on 2021-02-12 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0011_lineagestest_most_common_countries'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineagestest',
            name='most_common_countries',
        ),
    ]
