# Generated by Django 3.1.3 on 2021-02-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0012_remove_lineagestest_most_common_countries'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineagesMostCommonCountries',
            fields=[
                ('id_uvigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('id_process', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('country', models.TextField(blank=True, default=None, max_length=50)),
            ],
        ),
    ]
