# Generated by Django 3.1.3 on 2021-02-12 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0013_lineagesmostcommoncountries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagesmostcommoncountries',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='lineagestest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='nextcladetest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='ngsstatstest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='picardtest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='singlechecktest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='variantstest',
            name='id_process',
            field=models.CharField(max_length=40),
        ),
    ]
