# Generated by Django 3.1.3 on 2021-02-13 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0014_auto_20210212_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantstest',
            name='row',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='variantstest',
            unique_together={('id_uvigo', 'id_process', 'date', 'row')},
        ),
    ]
