# Generated by Django 3.1.3 on 2021-02-13 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0015_auto_20210213_0038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantstest',
            unique_together={('id_uvigo', 'id_process', 'date')},
        ),
        migrations.RemoveField(
            model_name='variantstest',
            name='row',
        ),
    ]
