# Generated by Django 3.1.3 on 2021-02-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0017_variantstest_row'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variantstest',
            table='my_author_table',
        ),
    ]
