# Generated by Django 3.1.3 on 2021-02-16 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0018_auto_20210216_1806'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='variantstest',
            table=None,
        ),
    ]
