# Generated by Django 3.1.3 on 2021-02-16 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0019_auto_20210216_1806'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantstest',
            unique_together={('id_uvigo', 'row', 'id_process', 'date')},
        ),
    ]
