# Generated by Django 3.1.3 on 2021-02-16 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0024_auto_20210216_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variantstest',
            name='id',
        ),
        migrations.AlterField(
            model_name='variantstest',
            name='id_uvigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
