# Generated by Django 3.1.3 on 2021-02-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0025_auto_20210216_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantstest',
            name='id_process',
            field=models.CharField(max_length=41),
        ),
    ]
