# Generated by Django 3.1.3 on 2021-02-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0026_auto_20210216_1904'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='variantstest',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='variantstest',
            constraint=models.UniqueConstraint(fields=('id_uvigo', 'row', 'id_process', 'date'), name='unique_constraint'),
        ),
    ]
