# Generated by Django 3.1.3 on 2021-02-16 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0028_auto_20210216_1909'),
    ]

    operations = [
        migrations.DeleteModel(
            name='VariantsTest',
        ),
    ]
