# Generated by Django 3.1.3 on 2021-03-03 02:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0031_auto_20210222_2216'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineagesMostCommonCountries',
        ),
        migrations.DeleteModel(
            name='LineagesTest',
        ),
        migrations.DeleteModel(
            name='NextcladeTest',
        ),
        migrations.DeleteModel(
            name='NGSstatsTest',
        ),
        migrations.DeleteModel(
            name='PicardTest',
        ),
        migrations.DeleteModel(
            name='SingleCheckTest',
        ),
        migrations.DeleteModel(
            name='VariantsTest',
        ),
    ]
