# Generated by Django 3.1.3 on 2021-03-03 02:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('upload', '0030_sample_id_region'),
        ('tests', '0032_auto_20210303_0256'),
    ]

    operations = [
        migrations.CreateModel(
            name='PicardTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.CharField(max_length=40)),
                ('mean_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('median_target_coverage', models.DecimalField(decimal_places=6, max_digits=15)),
                ('pct_target_bases_1x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_10x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('pct_target_bases_100x', models.DecimalField(decimal_places=6, max_digits=7)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_uvigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample')),
            ],
            options={
                'unique_together': {('id_uvigo', 'id_process', 'date')},
            },
        ),
    ]
