# Generated by Django 3.1.3 on 2021-03-03 03:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('upload', '0031_auto_20210303_0301'),
        ('tests', '0033_picardtest'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantsTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.CharField(max_length=41)),
                ('row', models.IntegerField()),
                ('pos', models.IntegerField()),
                ('ref', models.CharField(max_length=10)),
                ('alt', models.CharField(max_length=10)),
                ('alt_freq', models.DecimalField(decimal_places=6, max_digits=7)),
                ('ref_codon', models.CharField(max_length=10)),
                ('ref_aa', models.CharField(max_length=10)),
                ('alt_codon', models.CharField(max_length=10)),
                ('alt_aa', models.CharField(max_length=10)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_uvigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample')),
            ],
        ),
        migrations.CreateModel(
            name='SingleCheckTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.CharField(max_length=40)),
                ('autocorrelation', models.DecimalField(decimal_places=10, max_digits=15)),
                ('variation_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('gini_coefficient', models.DecimalField(decimal_places=10, max_digits=15)),
                ('mad', models.DecimalField(decimal_places=10, max_digits=15)),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_uvigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample')),
            ],
        ),
        migrations.CreateModel(
            name='NGSstatsTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.CharField(max_length=40)),
                ('total_reads', models.IntegerField()),
                ('mapped', models.IntegerField()),
                ('trimmed', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_uvigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample')),
            ],
        ),
        migrations.CreateModel(
            name='NextcladeTest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_process', models.CharField(max_length=40)),
                ('total_missing', models.IntegerField()),
                ('clade', models.TextField()),
                ('qc_private_mutations_status', models.TextField()),
                ('qc_missing_data_status', models.TextField()),
                ('qc_snp_clusters_status', models.TextField()),
                ('qc_mixed_sites_status', models.TextField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('id_uvigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='upload.sample')),
            ],
        ),
        migrations.AddConstraint(
            model_name='variantstest',
            constraint=models.UniqueConstraint(fields=('id_uvigo', 'row', 'id_process', 'date'), name='unique_constraint'),
        ),
        migrations.AlterUniqueTogether(
            name='singlechecktest',
            unique_together={('id_uvigo', 'id_process', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='ngsstatstest',
            unique_together={('id_uvigo', 'id_process', 'date')},
        ),
        migrations.AlterUniqueTogether(
            name='nextcladetest',
            unique_together={('id_uvigo', 'id_process', 'date')},
        ),
    ]
