# Generated by Django 3.1.3 on 2021-03-03 03:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0035_lineagesmostcommoncountries_lineagestest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineagesMostCommonCountries',
        ),
    ]
