# Generated by Django 3.1.3 on 2021-03-26 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0037_lineagesmostcommoncountries'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPrueba',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('id_uvigo', models.CharField(max_length=40)),
                ('atr1', models.CharField(max_length=10)),
                ('atr2', models.CharField(max_length=10)),
                ('atr3', models.CharField(max_length=10)),
                ('atr4', models.CharField(max_length=10)),
            ],
        ),
    ]
