# Generated by Django 3.1.3 on 2021-03-26 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0038_modeloprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloPrueba',
        ),
    ]
