# Generated by Django 3.1.3 on 2021-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0041_delete_modeloprueba'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModeloPrueba',
            fields=[
                ('id_uvigo', models.IntegerField(max_length=40, primary_key=True, serialize=False)),
                ('atr1', models.CharField(max_length=10)),
                ('atr2', models.CharField(max_length=10)),
                ('atr3', models.CharField(max_length=10)),
                ('atr4', models.CharField(max_length=10)),
            ],
        ),
    ]
