# Generated by Django 3.1.3 on 2021-03-26 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0042_modeloprueba'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modeloprueba',
            name='id_uvigo',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
