# Generated by Django 3.1.3 on 2021-03-26 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0043_auto_20210326_1555'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloPrueba',
        ),
    ]
