# Generated by Django 3.1.3 on 2021-03-27 00:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0045_modeloprueba'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModeloPrueba',
        ),
    ]
