# Generated by Django 3.1.3 on 2021-03-28 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0047_auto_20210328_2339'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineagesmostcommoncountries',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lineagestest',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nextcladetest',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ngsstatstest',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='picardtest',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='singlechecktest',
            name='id_process',
            field=models.CharField(default=None, max_length=40),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variantstest',
            name='id_process',
            field=models.CharField(default=None, max_length=41),
            preserve_default=False,
        ),
    ]
