# Generated by Django 3.1.3 on 2021-03-28 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0050_auto_20210328_2343'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picardtest',
            name='id_process',
        ),
    ]
