# Generated by Django 3.1.3 on 2021-04-05 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0061_auto_20210328_2347'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineagesmostcommoncountries',
            unique_together={('id_uvigo', 'country')},
        ),
    ]
