# Generated by Django 3.1.3 on 2021-04-05 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0062_auto_20210405_0950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagesmostcommoncountries',
            name='country',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
