# Generated by Django 3.1.3 on 2021-04-05 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0063_auto_20210405_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagestest',
            name='comments',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lineagestest',
            name='pangolearn_version',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
