# Generated by Django 3.1.3 on 2021-04-05 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0064_auto_20210405_0957'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LineagesMostCommonCountries',
        ),
    ]
