# Generated by Django 3.1.3 on 2021-04-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0065_delete_lineagesmostcommoncountries'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='lineagestest',
            name='countries',
            field=models.ManyToManyField(to='tests.Country'),
        ),
    ]
