# Generated by Django 3.1.3 on 2021-04-05 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0066_auto_20210405_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lineagestest',
            name='countries',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
    ]
