# Generated by Django 3.1.3 on 2021-04-05 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0067_auto_20210405_1016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('name', models.CharField(max_length=30, primary_key=True, serialize=False)),
            ],
        ),
        migrations.AddField(
            model_name='lineagestest',
            name='countries',
            field=models.ManyToManyField(to='tests.Country'),
        ),
    ]
