# Generated by Django 3.1.3 on 2021-04-05 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0068_auto_20210405_1017'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='lineagestest',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lineagestest',
            name='countries',
        ),
        migrations.RemoveField(
            model_name='lineagestest',
            name='id_uvigo',
        ),
        migrations.DeleteModel(
            name='Country',
        ),
        migrations.DeleteModel(
            name='LineagesTest',
        ),
    ]
