# Generated by Django 3.1.3 on 2021-04-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0070_country_lineagestest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lineagestest',
            old_name='countries',
            new_name='most_common_countries',
        ),
    ]
