# Generated by Django 3.1.3 on 2021-04-11 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0075_auto_20210411_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nextcladetest',
            name='total_missing',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
