# Generated by Django 3.1.3 on 2021-05-05 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0078_auto_20210419_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineagestest',
            name='conflict',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='lineagestest',
            name='most_common_countries',
            field=models.ManyToManyField(blank=True, null=True, to='tests.Country'),
        ),
        migrations.AlterField(
            model_name='lineagestest',
            name='probability',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=7, null=True),
        ),
    ]
