# Generated by Django 3.1.3 on 2021-05-05 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0080_auto_20210505_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lineagestest',
            name='comments',
            field=models.TextField(blank=True, default=None, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='lineagestest',
            name='most_common_countries',
            field=models.ManyToManyField(blank=True, to='tests.Country'),
        ),
    ]
