# Generated by Django 3.1.3 on 2021-06-27 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0082_auto_20210617_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcladetest',
            name='qc_overall_status',
            field=models.CharField(blank=True, default=None, max_length=30),
        ),
    ]
