# Generated by Django 3.1.3 on 2021-07-13 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0085_auto_20210713_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='nextcladetest',
            name='missing_on_target',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
